FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu


RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends git \
    && apt-get -y install build-essential \
    && apt-get -y install telnet \
    && apt-get -y install htop \
    && apt-get -y install tree \
    && apt-get -y install unzip \
    && apt-get -y install vim \
    && apt-get clean && rm -rf /var/lib/apt/lists/* 

WORKDIR /workspace